author: Hannah Schoenborn

email: hannah@plateofplants.com

title: Plate of Plants

name: Plate of Plants

description: Making plant based cooking simple. Learn to take your vegetables from garden to gourmet. Tons of free vegan recipes and tips!

baseurl: ''

url: http://plateofplants.com

disqus: plateofplants

cdn: https://plateofplants.github.io
skip_baseurl_with_cdn: false
skip_prefix_with_cdn: false
prefix: "/assets"

permalink: /:title

paginate: 10

markdown: kramdown

gems:
- jekyll-assets
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji

exclude:
- CNAME
- Gemfile
- Rakefile

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
